# Whether this GitHub repo is engineering related
engineering_project: true
# Name of the repository/project in English
english_name: CC Vocabulary fonts
# All technologies used
technologies: Sass, JavaScript, Webpack, Storybook
# Whether this repository should be featured on the CC Open Source site
featured: true
# Slack channel name
slack: "cc-dev-vocabulary"
